apiVersion: v1
kind: Service
metadata:
  name: websocket-server-service
  namespace: test
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
spec:
  selector:
    app: websocket-server
    namespace: test
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
